/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tierProps".
 */
export type TierProps = ('Free' | 'Basic' | 'Pro' | 'Enterprise') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    customers: Customer;
    categories: Category;
    lessons: Lesson;
    courses: Course;
    'course-enrollments': CourseEnrollment;
    'quiz-attempts': QuizAttempt;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'course-enrollments': CourseEnrollmentsSelect<false> | CourseEnrollmentsSelect<true>;
    'quiz-attempts': QuizAttemptsSelect<false> | QuizAttemptsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  avatar?: (number | null) | Media;
  roles?: ('admin' | 'editor' | 'instructor' | 'user')[] | null;
  /**
   * Profile information for instructors
   */
  instructorProfile?: {
    /**
     * Public display name (defaults to email if not set)
     */
    displayName?: string | null;
    /**
     * Short professional tagline or title
     */
    tagline?: string | null;
    /**
     * Instructor biography (max 1000 characters)
     */
    bio?: string | null;
    /**
     * Areas of expertise
     */
    expertise?: (number | Category)[] | null;
    /**
     * Years of professional experience
     */
    yearsExperience?: number | null;
    /**
     * Social media and professional profiles
     */
    socialLinks?: {
      website?: string | null;
      linkedin?: string | null;
      twitter?: string | null;
      github?: string | null;
      youtube?: string | null;
    };
    /**
     * Educational qualifications and certifications
     */
    qualifications?:
      | {
          title: string;
          institution: string;
          year?: number | null;
          type?: ('degree' | 'certification' | 'diploma' | 'course') | null;
          /**
           * Link to credential verification (optional)
           */
          verificationUrl?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Make profile visible on instructor directory
     */
    isPublicProfile?: boolean | null;
  };
  /**
   * Auto-calculated instructor statistics
   */
  instructorStats?: {
    /**
     * Total number of courses created
     */
    totalCourses?: number | null;
    /**
     * Total unique students enrolled across all courses
     */
    totalStudents?: number | null;
    /**
     * Average rating across all courses (0-5)
     */
    averageRating?: number | null;
    /**
     * Total number of reviews received
     */
    totalReviews?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  tier?: TierProps;
  /**
   * Total XP earned across all courses
   */
  totalXP?: number | null;
  /**
   * User level based on total XP
   */
  level?: number | null;
  enrolledCourses?: (number | CourseEnrollment)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-enrollments".
 */
export interface CourseEnrollment {
  id: number;
  customer: number | Customer;
  course: number | Course;
  enrolledAt: string;
  status: 'active' | 'completed' | 'paused' | 'dropped';
  /**
   * Course completion percentage
   */
  progress?: number | null;
  /**
   * Total XP earned in this course
   */
  totalXPEarned?: number | null;
  lastAccessedAt?: string | null;
  completedAt?: string | null;
  /**
   * Lessons marked as completed
   */
  completedLessons?: (number | Lesson)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug: string;
  /**
   * Brief description for course listings (max 300 characters)
   */
  shortDescription?: string | null;
  thumbnail: number | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Course instructor / author
   */
  instructor: number | User;
  category?: (number | null) | Category;
  level: 'beginner' | 'intermediate' | 'advanced';
  pricingType: 'free' | 'premium';
  /**
   * Set to 0 for free courses.
   */
  price?: number | null;
  featured?: boolean | null;
  /**
   * Course chapters containing lessons
   */
  chapters: {
    chapterTitle: string;
    chapterDescription?: string | null;
    lessons: (number | Lesson)[];
    id?: string | null;
  }[];
  learningOutcomes?:
    | {
        outcome: string;
        id?: string | null;
      }[]
    | null;
  prerequisites?:
    | {
        prerequisite: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Total XP available in this course, Auto-calculated from its lessons.
   */
  totalXP?: number | null;
  /**
   * Estimated duration to complete the course in hours.
   */
  estimatedDuration?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  /**
   * Associate this lesson with a course
   */
  course: number | Course;
  /**
   * Auto-populated from the selected course
   */
  instructor?: (number | null) | User;
  lessonName: string;
  /**
   * Lesson duration in minutes
   */
  duration: number;
  /**
   * Order within the chapter
   */
  order: number;
  /**
   * Brief lesson description
   */
  description?: string | null;
  /**
   * Allow non-enrolled users to preview this lesson
   */
  isPreview?: boolean | null;
  curriculum: (
    | {
        videoTitle: string;
        /**
         * Bunny.net embedded video URL
         */
        videoURL: string;
        /**
         * Video duration in minutes
         */
        videoDuration?: number | null;
        /**
         * Video thumbnail (optional)
         */
        thumbnail?: (number | null) | Media;
        /**
         * Video transcript for accessibility
         */
        transcript?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'lessonVideo';
      }
    | {
        contentTitle: string;
        /**
         * Main lesson content (text, images, code blocks, etc.)
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'lessonContent';
      }
    | {
        materialsTitle?: string | null;
        materials: {
          materialName: string;
          file: number | Media;
          fileType?: ('pdf' | 'doc' | 'sheet' | 'code' | 'archive' | 'other') | null;
          description?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'lessonMaterials';
      }
    | {
        quizTitle: string;
        /**
         * Instructions for the quiz
         */
        quizDescription?: string | null;
        /**
         * Minimum score percentage to pass
         */
        passingScore: number;
        questions: {
          question: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          questionType: 'multiple-choice' | 'true-false' | 'short-answer';
          /**
           * XP points awarded for correct answer
           */
          xpPoints: number;
          options?:
            | {
                optionText: string;
                isCorrect?: boolean | null;
                id?: string | null;
              }[]
            | null;
          /**
           * Sample correct answer (for reference)
           */
          correctAnswer?: string | null;
          /**
           * Explanation shown after answering
           */
          explanation?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'lessonQuiz';
      }
  )[];
  /**
   * Total XP available in this lesson (auto-calculated)
   */
  totalLessonXP?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-attempts".
 */
export interface QuizAttempt {
  id: number;
  customer: number | Customer;
  enrollment: number | CourseEnrollment;
  lesson: number | Lesson;
  /**
   * ID of the quiz block within the lesson
   */
  quizBlockId: string;
  answers: {
    questionIndex: number;
    answer:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    isCorrect?: boolean | null;
    xpAwarded?: number | null;
    id?: string | null;
  }[];
  /**
   * Score percentage
   */
  score: number;
  xpEarned: number;
  passed?: boolean | null;
  attemptedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title?: string | null;
  /**
   * If checked, this page will be set as the homepage of the website. Only one page can be the homepage at a time.
   */
  isHomepage?: boolean | null;
  slug?: string | null;
  description?: string | null;
  content?: {
    sections?:
      | (
          | {
              content: {
                /**
                 * Small text above the main heading (e.g., "Every Course,")
                 */
                preHeading?: string | null;
                /**
                 * Main hero heading (e.g., "Every Skill — One")
                 */
                heading: string;
                /**
                 * Text to highlight in different color (e.g., "Powerful Platform.")
                 */
                highlightedText?: string | null;
                highlightColor?: ('orange' | 'emerald' | 'teal' | 'purple' | 'blue') | null;
                /**
                 * Supporting text below the heading
                 */
                description: string;
                cta?: {
                  enabled?: boolean | null;
                  label?: string | null;
                  linkType?: ('internal' | 'external') | null;
                  internalLink?: (number | null) | Page;
                  externalLink?: string | null;
                };
              };
              image: {
                /**
                 * Upload the hero image (recommended: 800x900px)
                 */
                media: number | Media;
              };
              statistics?: {
                enabled?: boolean | null;
                stats?:
                  | {
                      label: string;
                      /**
                       * You can use numbers with + suffix or any format
                       */
                      value: string;
                      icon?: ('none' | 'book' | 'users' | 'award' | 'star' | 'graduation' | 'target') | null;
                      /**
                       * Make this stat stand out with different styling
                       */
                      highlighted?: boolean | null;
                      id?: string | null;
                    }[]
                  | null;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'hero';
            }
          | {
              content: {
                /**
                 * Small text above the main heading (e.g., "Popular Categories,")
                 */
                preHeading?: string | null;
                /**
                 * Main hero heading (e.g., "Explore Our Most-Loved")
                 */
                heading: string;
                /**
                 * Text to highlight in different color (e.g., "Learning Paths.")
                 */
                highlightedText?: string | null;
                highlightColor?: ('orange' | 'emerald' | 'teal' | 'purple' | 'blue') | null;
                /**
                 * Supporting text below the heading
                 */
                description: string;
                cta?: {
                  enabled?: boolean | null;
                  label?: string | null;
                  linkType?: ('internal' | 'external') | null;
                  internalLink?: (number | null) | Page;
                  externalLink?: string | null;
                };
              };
              topCategories: (number | Category)[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'topCategories';
            }
          | {
              content: {
                /**
                 * Hero image showing on the About section
                 */
                sectionImage?: (number | null) | Media;
                /**
                 * Small text above the main heading (e.g., "About Learnville")
                 */
                preHeading?: string | null;
                /**
                 * Main hero heading (e.g., "One Platform. Infinite")
                 */
                heading: string;
                /**
                 * Text to highlight in different color (e.g., "Learning Possibilities")
                 */
                highlightedText?: string | null;
                highlightColor?: ('orange' | 'emerald' | 'teal' | 'purple' | 'blue') | null;
                /**
                 * Supporting text below the heading
                 */
                description: string;
                cta?: {
                  enabled?: boolean | null;
                  label?: string | null;
                  linkType?: ('internal' | 'external') | null;
                  internalLink?: (number | null) | Page;
                  externalLink?: string | null;
                };
              };
              aboutStats?: {
                statsEnabled?: boolean | null;
                /**
                 * E.g., "100K+"
                 */
                activeLearners?: string | null;
                /**
                 * E.g., "500+"
                 */
                expertInstructors?: string | null;
              };
              aboutFeatures?: {
                featuresList?:
                  | {
                      title?: string | null;
                      description?: string | null;
                      id?: string | null;
                    }[]
                  | null;
              };
              layout?: ('image-left' | 'image-right') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'about';
            }
        )[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'course-enrollments';
        value: number | CourseEnrollment;
      } | null)
    | ({
        relationTo: 'quiz-attempts';
        value: number | QuizAttempt;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  roles?: T;
  instructorProfile?:
    | T
    | {
        displayName?: T;
        tagline?: T;
        bio?: T;
        expertise?: T;
        yearsExperience?: T;
        socialLinks?:
          | T
          | {
              website?: T;
              linkedin?: T;
              twitter?: T;
              github?: T;
              youtube?: T;
            };
        qualifications?:
          | T
          | {
              title?: T;
              institution?: T;
              year?: T;
              type?: T;
              verificationUrl?: T;
              id?: T;
            };
        isPublicProfile?: T;
      };
  instructorStats?:
    | T
    | {
        totalCourses?: T;
        totalStudents?: T;
        averageRating?: T;
        totalReviews?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  tier?: T;
  totalXP?: T;
  level?: T;
  enrolledCourses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  course?: T;
  instructor?: T;
  lessonName?: T;
  duration?: T;
  order?: T;
  description?: T;
  isPreview?: T;
  curriculum?:
    | T
    | {
        lessonVideo?:
          | T
          | {
              videoTitle?: T;
              videoURL?: T;
              videoDuration?: T;
              thumbnail?: T;
              transcript?: T;
              id?: T;
              blockName?: T;
            };
        lessonContent?:
          | T
          | {
              contentTitle?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        lessonMaterials?:
          | T
          | {
              materialsTitle?: T;
              materials?:
                | T
                | {
                    materialName?: T;
                    file?: T;
                    fileType?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        lessonQuiz?:
          | T
          | {
              quizTitle?: T;
              quizDescription?: T;
              passingScore?: T;
              questions?:
                | T
                | {
                    question?: T;
                    questionType?: T;
                    xpPoints?: T;
                    options?:
                      | T
                      | {
                          optionText?: T;
                          isCorrect?: T;
                          id?: T;
                        };
                    correctAnswer?: T;
                    explanation?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  totalLessonXP?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  thumbnail?: T;
  description?: T;
  instructor?: T;
  category?: T;
  level?: T;
  pricingType?: T;
  price?: T;
  featured?: T;
  chapters?:
    | T
    | {
        chapterTitle?: T;
        chapterDescription?: T;
        lessons?: T;
        id?: T;
      };
  learningOutcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  prerequisites?:
    | T
    | {
        prerequisite?: T;
        id?: T;
      };
  totalXP?: T;
  estimatedDuration?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-enrollments_select".
 */
export interface CourseEnrollmentsSelect<T extends boolean = true> {
  customer?: T;
  course?: T;
  enrolledAt?: T;
  status?: T;
  progress?: T;
  totalXPEarned?: T;
  lastAccessedAt?: T;
  completedAt?: T;
  completedLessons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-attempts_select".
 */
export interface QuizAttemptsSelect<T extends boolean = true> {
  customer?: T;
  enrollment?: T;
  lesson?: T;
  quizBlockId?: T;
  answers?:
    | T
    | {
        questionIndex?: T;
        answer?: T;
        isCorrect?: T;
        xpAwarded?: T;
        id?: T;
      };
  score?: T;
  xpEarned?: T;
  passed?: T;
  attemptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  isHomepage?: T;
  slug?: T;
  description?: T;
  content?:
    | T
    | {
        sections?:
          | T
          | {
              hero?:
                | T
                | {
                    content?:
                      | T
                      | {
                          preHeading?: T;
                          heading?: T;
                          highlightedText?: T;
                          highlightColor?: T;
                          description?: T;
                          cta?:
                            | T
                            | {
                                enabled?: T;
                                label?: T;
                                linkType?: T;
                                internalLink?: T;
                                externalLink?: T;
                              };
                        };
                    image?:
                      | T
                      | {
                          media?: T;
                        };
                    statistics?:
                      | T
                      | {
                          enabled?: T;
                          stats?:
                            | T
                            | {
                                label?: T;
                                value?: T;
                                icon?: T;
                                highlighted?: T;
                                id?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
              topCategories?:
                | T
                | {
                    content?:
                      | T
                      | {
                          preHeading?: T;
                          heading?: T;
                          highlightedText?: T;
                          highlightColor?: T;
                          description?: T;
                          cta?:
                            | T
                            | {
                                enabled?: T;
                                label?: T;
                                linkType?: T;
                                internalLink?: T;
                                externalLink?: T;
                              };
                        };
                    topCategories?: T;
                    id?: T;
                    blockName?: T;
                  };
              about?:
                | T
                | {
                    content?:
                      | T
                      | {
                          sectionImage?: T;
                          preHeading?: T;
                          heading?: T;
                          highlightedText?: T;
                          highlightColor?: T;
                          description?: T;
                          cta?:
                            | T
                            | {
                                enabled?: T;
                                label?: T;
                                linkType?: T;
                                internalLink?: T;
                                externalLink?: T;
                              };
                        };
                    aboutStats?:
                      | T
                      | {
                          statsEnabled?: T;
                          activeLearners?: T;
                          expertInstructors?: T;
                        };
                    aboutFeatures?:
                      | T
                      | {
                          featuresList?:
                            | T
                            | {
                                title?: T;
                                description?: T;
                                id?: T;
                              };
                        };
                    layout?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: {
    image: number | Media;
    alt?: string | null;
  };
  topBanner: {
    enabled?: boolean | null;
    backgroundColor?: ('teal' | 'blue' | 'purple' | 'red' | 'orange') | null;
    message: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    closeable?: boolean | null;
  };
  search?: {
    placeholder?: string | null;
    enabled?: boolean | null;
  };
  navigationLinks?:
    | {
        label: string;
        type: 'page' | 'external' | 'custom';
        page?: (number | null) | Page;
        url?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  exploreMenu?: {
    enabled?: boolean | null;
    label?: string | null;
    /**
     * Select categories to display in the Explore dropdown
     */
    categories?: (number | Category)[] | null;
    viewAllLink?: {
      enabled?: boolean | null;
      label?: string | null;
      page?: (number | null) | Page;
    };
  };
  ctaButtons?: {
    loginButton?: {
      label?: string | null;
      url?: string | null;
    };
    signupButton?: {
      label?: string | null;
      url?: string | null;
    };
    myAccountButton?: {
      label?: string | null;
      url?: string | null;
    };
  };
  mobileMenu?: {
    enabled?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo: number | Media;
  tagline: string;
  socials?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  newsletter: {
    title: string;
    description?: string | null;
    placeholder?: string | null;
    buttonText?: string | null;
  };
  linkColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              type: 'internal' | 'external' | 'category';
              internalLink?: (number | null) | Page;
              categoryLink?: (number | null) | Category;
              externalLink?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contactInfo?: {
    title?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  copyright?: {
    text?: string | null;
    designer?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        image?: T;
        alt?: T;
      };
  topBanner?:
    | T
    | {
        enabled?: T;
        backgroundColor?: T;
        message?: T;
        closeable?: T;
      };
  search?:
    | T
    | {
        placeholder?: T;
        enabled?: T;
      };
  navigationLinks?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  exploreMenu?:
    | T
    | {
        enabled?: T;
        label?: T;
        categories?: T;
        viewAllLink?:
          | T
          | {
              enabled?: T;
              label?: T;
              page?: T;
            };
      };
  ctaButtons?:
    | T
    | {
        loginButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
        signupButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
        myAccountButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  mobileMenu?:
    | T
    | {
        enabled?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  tagline?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        placeholder?: T;
        buttonText?: T;
      };
  linkColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              type?: T;
              internalLink?: T;
              categoryLink?: T;
              externalLink?: T;
              id?: T;
            };
        id?: T;
      };
  contactInfo?:
    | T
    | {
        title?: T;
        email?: T;
        phone?: T;
        address?: T;
      };
  copyright?:
    | T
    | {
        text?: T;
        designer?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}